using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bistro.Validation
{
    /// <summary>
    /// Marks a class as supporting validation
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public interface IValidatable
    {
        /// <summary>
        /// Gets or sets the messages generated by validating this instance.
        /// </summary>
        /// <value>The messages.</value>
        List<IValidationResult> Messages { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is valid.
        /// </summary>
        /// <value><c>true</c> if this instance is valid; otherwise, <c>false</c>.</value>
        bool IsValid { get; set; }
    }
}
